=== mmalher/mmalher.github.io/assignments/assignment3/algreen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT CD_cover (front, back)>
<!ELEMENT front (#PCDATA)>
<!ELEMENT  back (left-sidebar, middle, right-sidebar)+ >
<!ELEMENT  left-sidebar (image+, title+) >
<!ATTLIST left-sidebar background-color CDATA #IMPLIED >
<!ELEMENT image (#PCDATA)>
<!ATTLIST image ref CDATA #IMPLIED>
<!ELEMENT  title ANY >
<!ATTLIST title style CDATA #IMPLIED >
<!ELEMENT  middle (top-half+, bottom-half+) >
<!ATTLIST middle background-color CDATA #IMPLIED >
<!ELEMENT top-half (tracklisting+, technologies+, record_credits+)>
<!ELEMENT tracklisting (list+) >
<!ATTLIST tracklisting position CDATA #IMPLIED >
<!ELEMENT  list (song+) >
<!ELEMENT song (song_title+, song_credits+, PRO+)>
<!ELEMENT song_title (#PCDATA) >
<!ATTLIST song_title style CDATA #IMPLIED >
<!ATTLIST  song_title type CDATA #IMPLIED >
<!ELEMENT  song_credits (#PCDATA) >
<!ELEMENT PRO (#PCDATA)>
<!ELEMENT  technologies (image+) >
<!ELEMENT record_credits (job+, recorded_at+)>
<!ATTLIST record_credits position CDATA #REQUIRED >
<!ELEMENT  job (#PCDATA | name | instrument)* >
<!ELEMENT  job_title (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ATTLIST name type CDATA #IMPLIED>
<!ATTLIST job type CDATA #IMPLIED >
<!ATTLIST job style CDATA #IMPLIED >
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT recorded_at (location+)>
<!ELEMENT location (studio_name+,city+,state+)>
<!ELEMENT studio_name (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA) >
<!ELEMENT  right-sidebar (title+,image+) >
<!ATTLIST right-sidebar background-color CDATA #IMPLIED >
<!ELEMENT  bottom-half (image*) >

=== mmalher/mmalher.github.io/assignments/assignment3/algreen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CD_cover SYSTEM "mmalher.github.io/assignments/assignment3/algreen.dtd">
<CD_cover>
    <front> </front>
    <back>
        <left-sidebar background-color="red">
            <image ref="DVD_Video_Logo.jpg"/>
            <image ref="DTS_Logo.jpg"/>
            <image ref="DolbyDigital_Logo.jpg"/>
            <image ref="MLP_Logo.jpg"/>
            <image ref="DVD_Audio_Logo.jpg"/>
            <image ref="QQCC_Logo.jpg"/>
            <title style="sideways-all-caps">AL GREEN'S GREATEST HITS</title>
        </left-sidebar>
        <middle background-color="red">
            <top-half>
                <tracklisting position="right">
                    <list>
                        <song>
                            <song_title style="all-caps">TIRED OF BEING ALONE</song_title>
                            <song_credits>A. Green</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps" type="main">CALL ME</song_title>
                            <song_title type="parathesis">(COME BACK HOME)</song_title>
                            <song_credits>A. Green; W. Mitchell; AJackson</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">I'M STILL IN LOVE WITH YOU</song_title>
                            <song_credits>A. Green; W. Mitchell; AJackson</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps" type="main">HERE I AM</song_title>
                            <song_title type="parathesis">(COME AND TAKE ME)</song_title>
                            <song_credits>A. Green; M. Hodges</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">HOW CAN YOU MEND A BROKEN
                                HEART</song_title>
                            <song_credits>B. Gibb; R. Gibb</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">LET'S STAY TOGETHER</song_title>
                            <song_credits>A. Green; W. Mitchell; AJackson</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">I CAN'T GET NEXT TO YOU</song_title>
                            <song_credits>Whitfield; Strong</song_credits>
                            <PRO>ASCAP</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">YOU OUGHT TO BE WITH ME</song_title>
                            <song_credits>A. Green; W. Mitchell; A.Jackson</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">LOOK WHAT YOU DONE FOR ME</song_title>
                            <song_credits>A. Green; W. Mitchell; AJackson</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                        <song>
                            <song_title style="all-caps">LET'S GET MARRIED</song_title>
                            <song_credits>A. Green</song_credits>
                            <PRO>BMI</PRO>
                        </song>
                    </list>
                </tracklisting>
                <technologies>
                    <image ref="QQCC_Logo.jpg"/>
                    <image ref="DVD_Audio_Logo.jpg"/>
                    <image ref="MLP_Logo.jpg"/>
                    <image ref="DolbyDigital_Logo.jpg"/>
                    <image ref="DTS_Logo.jpg"/>
                    <image ref="DVD_Video_Logo.jpg"/>
                </technologies>
                <record_credits position="left">
                    <job type="title" style="all-caps">
                        PRODUCER:
                        <name>Willie
                            Mitchell</name>
                        <name>Al Green</name></job>
                    <job style="all-caps">
                        ENGINEER: 
                        <name>Willie Mitchell</name></job>
                    <job style="all-caps">
                        REMIX ENGINEER: 
                        <name>Willie Mitchell</name></job>
                    <job style="all-caps">VOCAL BACKGROUNDS:
                            <name>Rhodes</name><name>Chalmers</name><name>Rhodes</name></job>
                    <job style="all-caps">STRING ARRAMGEMENTS: <name>James
                            Mitchell</name><name>Charles Chalmers</name></job>
                    <job>STRING SECTION: <name type="band_name">The Memphis Strings</name></job>
                    <job style="all-caps">
                        HORN SECTION:
                        <name>Wayne Jackson</name>
                       <instrument>Trumpet</instrument>
                        
                        <name>Andrew Love</name>
                        <instrument>Tenor</instrument>
                        
                        <name>Ed Logan</name>
                        <instrument>Tenor</instrument>
                         <name>James Mitchell</name>
                         <instrument>Baritone Sax</instrument>
                         <name>Jack Hole</name>
                         <instrument>Trombone</instrument>
                         
                    </job>
                    
                    <job style="all-caps">
                        RHYTHM SECTION 
                        <name>Howard Grimes</name>
                        <name>Al Jackson</name>
                                <instrument>Drums</instrument>
                        <instrument>Congas</instrument>
                        <instrument>Bongo</instrument>
                    
                        <name>Leroy
                            Hodges</name> 
                    <instrument>Bass</instrument>
                    
                    <name>Charies Hodges</name>
                                <instrument>Organ</instrument>
                        <instrument>Piano</instrument>
                        <name>Teenie
                            Hodges</name> 
                        <instrument>Guitar</instrument>
                        <name>Archie Turner</name>
                                <instrument>Piano</instrument>
                                <name>Michael Allen</name>
                                <instrument>Piano</instrument>
                    </job>
                    <recorded_at>
                        <location>
                            <studio_name>Royal Recording Studios</studio_name>
                            <city>Memphis</city>
                            <state>TN</state>
                        </location>
                    </recorded_at>
                </record_credits>
            </top-half>
            <bottom-half>
                <image ref="al-green.jpg"/>
                <image ref="hi-records.jpg"/>
            </bottom-half>
        </middle>
        <right-sidebar background-color="red">
            <title style="sideways-all-caps">AL GREEN'S GREATEST HITS</title>
            <image ref="QQCC_Logo.jpg"/>
            <image ref="DVD_Audio_Logo.jpg"/>
            <image ref="MLP_Logo.jpg"/>
            <image ref="DolbyDigital_Logo.jpg"/>
            <image ref="DTS_Logo.jpg"/>
            <image ref="DVD_Video_Logo.jpg"/>
        </right-sidebar>
    </back>
</CD_cover>
